# Generated by Django 4.2.16 on 2024-10-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegeta', '0002_rename_title_post_subject_remove_post_title_tag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='subject',
            new_name='Subject',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='post',
            name='summary',
        ),
        migrations.AddField(
            model_name='post',
            name='Marks',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
