# Generated by Django 4.2.16 on 2024-10-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegeta', '0003_rename_subject_post_subject_remove_post_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Semester-1', max_length=255),
        ),
    ]
