# Generated by Django 4.2.16 on 2024-10-17 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegeta', '0004_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='Semester',
        ),
    ]
