# Generated by Django 4.2.16 on 2024-10-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegeta', '0006_alter_post_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
